common_folder: common
description: "Function for pump timeseries forecast"
owner: w.e.wu@accenture.com
cpu: 1.0
memory: 1.5
cdf_project: "accenture-tiger-training"
cdf_cluster: "api"
data_set_id: 5015282361972951 #ds name: cognite_replicator_test
#env_vars:
#  MY_ENV_VAR: "1337"
#  which_env: "p-p-p-production"
# Alternatively, env_vars: {"MY_ENV_VAR": "1337", "which_env": "p-p-p-production"}
# Parameters that are usually not needed to pass (they have good default values):
# function_file: handler.py  # Use case: Just don't...
# function_deploy_timeout: 1500  # Use case: CDF on Azure has slower deployment speed.
# post_deploy_cleanup: false  # Use case: You want to keep the uploaded zipped code files.
